In [1]:
import numpy as np

lst = [1, 2, 3, 4, 5, 6]
arr = np.array(lst)
print(arr.reshape(2, 3))
print(arr.reshape(2, 1, 3))


[[1 2 3]
 [4 5 6]]
[[[1 2 3]]

 [[4 5 6]]]


In [ ]:
rand_int = np.random.randint(1, 10, (3, 3))
print(rand_int)
rand_float = np.random.rand(2, 4)
print(rand_float)


In [ ]:
from scipy import linalg

mat = np.array([[2, 4], [1, 3]])
print(linalg.det(mat))


In [ ]:
eig_val, eig_vec = linalg.eig(mat)
print(eig_val)
print(eig_vec)


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({'x':[1,2,3,4], 'y':[10,20,25,30]})
plt.plot(df['x'], df['y'])
plt.show()


In [ ]:
s = pd.Series([10, 20, 30, 40])
print(s)


In [ ]:
print(s.index)
print(s.values)


In [ ]:
arr = np.array([1, 2, 3])
ser = pd.Series([1, 2, 3])
print(arr == 2)
print(ser == 2)


In [ ]:
s2 = pd.Series([100, 200, 300], index=['x', 'y', 'z'])
print(s2)


In [ ]:
print(s2['y'])


In [ ]:
df = pd.read_csv("sample.csv")
print(df.head())


In [ ]:
x = [1,2,3,4,5]
y = [10,20,25,30,40]

import matplotlib.pyplot as plt
plt.plot(x, y)
plt.show()
plt.bar(x, y)
plt.show()
plt.scatter(x, y)
plt.show()


In [ ]:
data = {'id':[1,2,3], 'name':['A','B','C'], 'marks':[50,60,70]}
df1 = pd.DataFrame(data)
print(df1)


In [ ]:
df2 = pd.read_csv("sample.csv")
print(df2)


In [ ]:
from sklearn import datasets

iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
print(iris_df.head())


In [ ]:
from scipy import stats

marks = df1['marks']
print(marks.mean())
print(marks.median())
print(stats.mode(marks))
print(marks.var())
print(marks.std())


In [ ]:
reshaped = df1.values.reshape(3,1,3)
print(reshaped)


In [ ]:
filtered = df1[df1['marks'] > 55]
print(filtered)


In [ ]:
extra = pd.DataFrame({'id':[4,5], 'name':['D','E'], 'marks':[80,90]})
merged = pd.concat([df1, extra])
print(merged)


In [ ]:
df_missing = df1.copy()
df_missing.loc[1,'marks'] = np.nan
print(df_missing.fillna(df_missing['marks'].mean()))


In [ ]:
df_norm = (df1['marks'] - df1['marks'].min()) / (df1['marks'].max() - df1['marks'].min())
print(df_norm)


In [ ]:
print(df.describe())


In [ ]:
print(df['Marks'].describe())
print(df[['Marks','id']].corr())
